language: php

dist: trusty

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6
  - 7.4

matrix:
  allow_failures:
    - php: 7.3

install:
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi


before_script:
  - phpunit --version
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer update --lock

# omitting "script:" will default to phpunit
script:
  - phpunit --configuration phpunit_phpspo.xml --coverage-text
notifications:
  email: never

